# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import PySide2.QtWidgets
import PySide2.QtGui
import PySide2.QtCore
import platform
import uuid
import bs4
import requests
import Crypto.Cipher
import Crypto.Util.Padding
import datetime
import multiprocessing
import re
import psutil

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

